"""add coupon-credit relationship

Revision ID: 1b69df1f13e2
Revises: 2d32659e4ce5
Create Date: 2023-12-25 15:17:00.384510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b69df1f13e2'
down_revision: Union[str, None] = '2d32659e4ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('credit_card_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'credit_cards', ['credit_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'credit_card_id')
    # ### end Alembic commands ###
