"""add coupon-debit relationship

Revision ID: 2d32659e4ce5
Revises: 970c5b17d56a
Create Date: 2023-12-25 15:15:45.478408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d32659e4ce5'
down_revision: Union[str, None] = '970c5b17d56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('debit_card_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'debit_cards', ['debit_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'debit_card_id')
    # ### end Alembic commands ###
