"""Add foreign key to Coupon

Revision ID: 911ee16c23b9
Revises: f95c17b563da
Create Date: 2023-12-24 22:01:46.078660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911ee16c23b9'
down_revision: Union[str, None] = 'f95c17b563da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('credit_card_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'credit_cards', ['credit_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'credit_card_id')
    # ### end Alembic commands ###
