"""update Seat model

Revision ID: fb6f40a14710
Revises: 8f50f2459892
Create Date: 2023-12-25 23:11:43.302714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6f40a14710'
down_revision: Union[str, None] = '8f50f2459892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.alter_column('admins', 'address_line_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'address_line_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('seats', 'total_seats')
    op.alter_column('staff_members', 'address_line_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_members', 'address_line_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('seats', sa.Column('total_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('customers', 'address_line_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('admins', 'address_line_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('test',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('datetime_modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('datetime_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
