"""Add foreign key to Coupon-DebitCard

Revision ID: fc6a80795555
Revises: 911ee16c23b9
Create Date: 2023-12-24 23:42:39.251559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6a80795555'
down_revision: Union[str, None] = '911ee16c23b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('debit_card_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'debit_cards', ['debit_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'debit_card_id')
    # ### end Alembic commands ###
